# Generated by Django 3.2.5 on 2021-08-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('uploaded_img', models.ImageField(upload_to='uploaded_images/', verbose_name='Select an image to analyze')),
            ],
        ),
    ]
