# Generated by Django 3.2.6 on 2021-08-08 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('VIP', models.BooleanField(default=False)),
                ('is_allowed_in', models.BooleanField(default=True)),
                ('comments', models.CharField(default='', max_length=500)),
                ('total_entry_tickets_bought', models.PositiveSmallIntegerField(default=0)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('uploaded_img', models.ImageField(upload_to='uploaded_images/', verbose_name='Select an image to analyze')),
            ],
        ),
    ]
