# Generated by Django 3.2.6 on 2021-08-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimages',
            name='analyzed_img',
            field=models.ImageField(default=None, null=True, upload_to='analyzed_images/'),
        ),
    ]
