# Generated by Django 3.2.6 on 2021-08-02 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_analyzer', '0002_uploadedimages_analyzed_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimages',
            name='analyzed_img',
        ),
    ]
